version: '3.8'

services:
  credit-application-service:
    build:
      context: ./credit-application-service
      dockerfile: Dockerfile
    ports:
      - "10001:5000"
    environment:
      - DB_HOST=${DB_HOST:-mysql}
      - DB_NAME=${DB_NAME:-credit_db}
      - DB_USER=${DB_USER:-credit_user}
      - DB_PASSWORD=${DB_PASSWORD:-credit_password}
      - DB_PORT=${DB_PORT:-3306}
    volumes:
      - ./credit-application-service:/app
    depends_on:
      - mysql
    restart: unless-stopped
    networks:
      - credit-network

  credit-info-service:
    build:
      context: ./credit-info-service
      dockerfile: Dockerfile
    ports:
      - "10002:5000"
    environment:
      - DB_HOST=${DB_HOST:-mysql}
      - DB_NAME=${DB_NAME:-credit_db}
      - DB_USER=${DB_USER:-credit_user}
      - DB_PASSWORD=${DB_PASSWORD:-credit_password}
      - DB_PORT=${DB_PORT:-3306}
    volumes:
      - ./credit-info-service:/app
    depends_on:
      - mysql
    restart: unless-stopped
    networks:
      - credit-network

  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=credit_db
      - MYSQL_USER=credit_user
      - MYSQL_PASSWORD=credit_password
    volumes:
      - mysql-data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d
    networks:
      - credit-network

volumes:
  mysql-data:

networks:
  credit-network:
    driver: bridge
