version: '3.8'

services:
  credit-application-service:
    build:
      context: ./credit-application-service
      dockerfile: Dockerfile
    ports:
      - "8081:5000"  # puerto host:container
    environment:
      - DB_HOST=the-bank-credito-solicitud-mysql-ins.cq9kcuq22hvr.us-east-1.rds.amazonaws.com
      - DB_NAME=credit_db
      - DB_USER=admin
      - DB_PASSWORD=lalilulelo
      - DB_PORT=3306
    volumes:
      - ./credit-application-service:/app
    restart: unless-stopped
    networks:
      - credit-network

  credit-info-service:
    build:
      context: ./credit-info-service
      dockerfile: Dockerfile
    ports:
      - "8082:5000"
    environment:
      - DB_HOST=the-bank-credito-solicitud-mysql-ins.cq9kcuq22hvr.us-east-1.rds.amazonaws.com
      - DB_NAME=credit_db
      - DB_USER=admin
      - DB_PASSWORD=lalilulelo
      - DB_PORT=3306
    volumes:
      - ./credit-info-service:/app
    restart: unless-stopped
    networks:
      - credit-network

networks:
  credit-network:
    driver: bridge
